apiVersion: v1
kind: Namespace
metadata:
  name: maposcal-demo
  labels:
    environment: development
    project: maposcal
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    environment: development
    component: monitoring
