"""
maposcal.generator.trestle_integration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compliance-trestle integration for MapOSCAL OSCAL generation.

This module provides functions to convert MapOSCAL's current OSCAL format
to compliance-trestle models for improved schema validation and type safety.

Key Features:
- Conversion from MapOSCAL dict format to compliance-trestle models
- Proper OSCAL schema validation
- Type-safe OSCAL generation
- Standardized serialization

Functions:
- convert_implemented_requirement: Convert single requirement to compliance-trestle model
- create_oscal_component: Create full OSCAL component definition
- validate_oscal_structure: Validate OSCAL structure using compliance-trestle
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
import uuid
import logging

from trestle.oscal.component import (
    ComponentDefinition,
    ImplementedRequirement,
    DefinedComponent,
    ControlImplementation,
    Statement
)
from trestle.oscal.common import Metadata, Property, Link

logger = logging.getLogger(__name__)


def convert_implemented_requirement(req_dict: Dict[str, Any]) -> ImplementedRequirement:
    """
    Convert a MapOSCAL implemented requirement dict to compliance-trestle model.
    
    Args:
        req_dict: MapOSCAL format implemented requirement dictionary
        
    Returns:
        ImplementedRequirement: Compliance-trestle model instance
        
    Raises:
        ValueError: If required fields are missing or invalid
    """
    try:
        # Convert properties
        props = []
        for prop_dict in req_dict.get('props', []):
            # Handle namespace validation for compliance-trestle
            ns = prop_dict.get('ns', 'https://compliance.engineering/ns/default')
            
            # Convert URN namespaces to HTTPS URLs for compliance-trestle
            if ns.startswith('urn:maposcal:'):
                ns = ns.replace('urn:maposcal:', 'https://compliance.engineering/ns/')
            elif ns.startswith('urn:'):
                # For other URNs, convert to a valid HTTPS URL
                ns = ns.replace('urn:', 'https://compliance.engineering/urn/')
            
            # Clean the value to ensure it meets compliance-trestle validation requirements
            # The regex pattern requires: ^\S(.*\S)?$ (starts and ends with non-whitespace)
            value = prop_dict['value']
            if isinstance(value, str):
                # Remove all types of whitespace characters (spaces, tabs, newlines, etc.)
                value = ' '.join(value.split())  # This normalizes all whitespace to single spaces
                if not value:  # If empty after cleaning, use a placeholder
                    value = "No value provided"
            elif isinstance(value, list):
                # Handle list values (like configuration arrays)
                value = str(value)  # Convert to string representation
            else:
                # Handle other types (numbers, booleans, etc.)
                value = str(value)
            
            prop = Property(
                name=prop_dict['name'],
                value=value,
                ns=ns
            )
            props.append(prop)
        
        # Convert statements
        statements = []
        for stmt_dict in req_dict.get('statements', []):
            stmt = Statement(
                statement_id=stmt_dict['statement-id'],
                uuid=stmt_dict['uuid'],
                description=stmt_dict.get('description', '')
            )
            statements.append(stmt)
        
        # Note: Annotations are not currently supported in compliance-trestle
        # Source code references would need to be handled differently
        # For now, we skip annotation conversion
        
        # Create the implemented requirement
        impl_req = ImplementedRequirement(
            uuid=req_dict['uuid'],
            control_id=req_dict['control-id'],
            description=req_dict.get('description', ''),
            props=props,
            statements=statements,
            remarks=req_dict.get('remarks')
        )
        
        return impl_req
        
    except KeyError as e:
        raise ValueError(f"Missing required field in implemented requirement: {e}")
    except Exception as e:
        raise ValueError(f"Error converting implemented requirement: {e}")


def create_oscal_component(
    implemented_requirements: List[Dict[str, Any]],
    component_title: str = "MapOSCAL Generated Component",
    component_description: str = "Component generated by MapOSCAL analysis",
    component_type: str = "application"
) -> ComponentDefinition:
    """
    Create a complete OSCAL component definition using compliance-trestle models.
    
    Args:
        implemented_requirements: List of MapOSCAL format implemented requirements
        component_title: Title for the component
        component_description: Description for the component
        component_type: Type of component (application, service, etc.)
        
    Returns:
        ComponentDefinition: Complete OSCAL component definition
        
    Raises:
        ValueError: If any requirements are invalid
    """
    try:
        # Convert all implemented requirements
        impl_reqs = []
        for req_dict in implemented_requirements:
            impl_req = convert_implemented_requirement(req_dict)
            impl_reqs.append(impl_req)
        
        # Create control implementation
        control_impl = ControlImplementation(
            uuid=str(uuid.uuid4()),
            source='NIST SP 800-53 Rev. 5',
            description='MapOSCAL generated control implementation',
            implemented_requirements=impl_reqs
        )
        
        # Create component
        component = DefinedComponent(
            uuid=str(uuid.uuid4()),
            type=component_type,
            title=component_title,
            description=component_description,
            control_implementations=[control_impl]
        )
        
        # Create metadata
        metadata = Metadata(
            title=component_title,
            version='1.0.0',
            last_modified=datetime.now().isoformat(),
            oscal_version='1.1.3'
        )
        
        # Create component definition
        comp_def = ComponentDefinition(
            uuid=str(uuid.uuid4()),
            metadata=metadata,
            components=[component]
        )
        
        return comp_def
        
    except Exception as e:
        logger.error(f"Error creating OSCAL component: {e}")
        raise


def validate_oscal_structure(comp_def: ComponentDefinition) -> bool:
    """
    Validate OSCAL structure using compliance-trestle validation.
    
    Args:
        comp_def: ComponentDefinition to validate
        
    Returns:
        bool: True if valid, False otherwise
    """
    try:
        # Compliance-trestle models validate on creation
        # This function provides additional validation if needed
        if not comp_def.uuid:
            return False
        
        if not comp_def.metadata:
            return False
        
        if not comp_def.components:
            return False
        
        # Validate each component
        for component in comp_def.components:
            if not component.control_implementations:
                return False
            
            for control_impl in component.control_implementations:
                if not control_impl.implemented_requirements:
                    return False
        
        return True
        
    except Exception as e:
        logger.error(f"OSCAL validation error: {e}")
        return False


def serialize_oscal_component(comp_def: ComponentDefinition, pretty: bool = True) -> str:
    """
    Serialize OSCAL component definition to JSON using compliance-trestle.
    
    Args:
        comp_def: ComponentDefinition to serialize
        pretty: Whether to pretty-print the JSON
        
    Returns:
        str: JSON string representation
    """
    try:
        return comp_def.oscal_serialize_json(pretty=pretty)
    except Exception as e:
        logger.error(f"Error serializing OSCAL component: {e}")
        raise


def create_oscal_component_from_maposcal_output(
    maposcal_output: Dict[str, Any]
) -> ComponentDefinition:
    """
    Create OSCAL component from MapOSCAL's current output format.
    
    Args:
        maposcal_output: MapOSCAL output dictionary with 'implemented_requirements'
        
    Returns:
        ComponentDefinition: Compliance-trestle OSCAL component
    """
    implemented_requirements = maposcal_output.get('implemented_requirements', [])
    
    if not implemented_requirements:
        raise ValueError("No implemented requirements found in MapOSCAL output")
    
    return create_oscal_component(implemented_requirements)
